haxtheweb/webcomponents

- .travis.yml
keeps dependencies that have previously been downloaded between test runs to avoid unneeded network calls to the package registry.
> preserve yarn cache between travis ci builds

- scripts/postinstall.sh
Use symlink-dir instead of ln -s, and added identification to line 12
> Use symbolic link for Cygwin compatibility

- elements/a11y-collapse/lib/a11y-collapse-group.js
- elements/hax-body/lib/hax-tray.js
- sets the a11y-collapse-group to radio mode and selects settings when content is added from tray.
- group listens for expand() method.
> Fix state management issue with the HAX tray

- elements/editable-outline/editable-outline.js
- elements/editable-outline/src/editable-outline.css
- elements/haxcms-elements/lib/core/haxcms-site-store.js
- elements/json-outline-schema/json-outline-schema.js
- elements/json-outline-schema/src/json-outline-schema.js
- elements/map-menu/lib/map-menu-builder.js
- elements/map-menu/lib/map-menu-item.js
- elements/map-menu/lib/map-menu-submenu.js
I added a check for authenticated users that will show them unpublished pages.  There is a "visibility-off" icon next to the map-menu item.  I also added an attribute in json-outline-schema to indicate if it's published.
In this example, the logged in user can see that "Week 3" is unpublished.  And non-logged in users don't see "Week 3"
> Unpublished navigation

- scripts/babel-plugin-dynamic-to-static-import.js
- scripts/rollup.config.factory.js
rollup currently does not support dynamic import in iife or umd builds.
this transforms dynamic imports to static imports to allow umd builds to continue to work.
an example of the input and output of the plugin can be seen here https://astexplorer.net/#/gist/16c8cd275ea5b0df3da862d2fb5add9a/8ce0535267e300bc149d78a9b738b5740df63a8b
> build: transform dynamic imports to static imports for umd build

- package.json
version 4.14.0 adds support for node 14.
https://github.com/sass/node-sass/releases/tag/v4.14.0
which should resolve ci/build issues on node 14, like:
https://github.com/elmsln/lrnwebcomponents/runs/1107048076
> chore: upgrade node sass to version 4.14.1

- .github/workflows/build.yml
- elements/a11y-figure/package.json
- elements/air-horn/package.json
- elements/elmsln-studio/package.json
- elements/exif-data/package.json
- elements/figure-label/package.json
- elements/git-corner/package.json
- elements/glossary-term/package.json
- elements/h5p-element/package.json
- elements/hax-logo/package.json
- elements/iframe-loader/package.json
- elements/lazy-import-discover/package.json
- elements/lrndesign-gallery/package.json
- elements/lrndesign-timeline/package.json
- elements/nav-card/package.json
- elements/portal-launcher/package.json
- elements/punnett-square/package.json
- elements/r-coder/package.json
- elements/random-item/package.json
- elements/rss-items/package.json
- elements/they-live/package.json
- elements/undo-manager/package.json
- package.json
tests are currently broken, running the tests adds 4 hours to each job in the matrix, removing it for now.
New test matrix
| operating system | node 14 | node 12 | node 10 |
| - | - | - | - |
| linux | :heavy_check_mark:  | :heavy_check_mark: | :heavy_check_mark: |
| macos | :heavy_check_mark: | :no_entry: | :no_entry:  |
| windows | :heavy_check_mark: | :no_entry: | :no_entry:  |
this ensures that all versions of node and all OS'es are tested, but reduces the number of jobs from 9 to 5.
([github actions limits free projects to running 20 concurrent jobs at a time, and 5 macos jobs at a time](https://docs.github.com/en/actions/getting-started-with-github-actions/about-github-actions#usage-limits))
> ci(github-actions): add macos to matrix, drop test script

- elements/lrnapp-fab-menu/package.json
I'm using `@lrnwebcomponents/lrnapp-fab-menu` in my project, and when I build it with rollup, it shows the following warning:
```
(!) Unresolved dependencies
@lrnwebcomponents/simple-icon/simple-icon.js (imported by node_modules/@lrnwebcomponents/lrnapp-fab-menu/lrnapp-fab-menu.js, node_modules/@lrnwebcomponents/lrnapp-fab-menu/lib/lrnapp-fab-speed-dial-action.js)
@lrnwebcomponents/simple-icon/lib/simple-icon-button.js (imported by node_modules/@lrnwebcomponents/lrnapp-fab-menu/lrnapp-fab-menu.js, node_modules/@lrnwebcomponents/lrnapp-fab-menu/lib/lrnapp-fab-speed-dial-action.js)
@lrnwebcomponents/simple-icon/lib/simple-icons.js (imported by node_modules/@lrnwebcomponents/lrnapp-fab-menu/lrnapp-fab-menu.js, node_modules/@lrnwebcomponents/lrnapp-fab-menu/lib/lrnapp-fab-speed-dial-action.js) …
```
> Fix simple-icon package.json placement

- elements/course-design/lib/activity-box.js
Allowing tag & slotted content in `<activity-box>` to be editable on page and within the left-hand pane (in a code editor).
Added a fix to allow the activity box to be large enough to contain the simple-icon (when using a default icon).
> Activity box updates

- elements/course-design/lib/activity-box.js
Fixed an issue which was causing HAX to become unresponsive when saving an activity box element with a non-empty tag.
HAX would be become unresponsive for several minutes when trying to save a page with an `activity-box` element which had a non-empty `tag`. It was throwing these errors in console:
I think this was because the `tag` div was being removed from the DOM completely when empty which was causing HAX to fail when adding/removing the `contenteditable` attribute to it as part of the hook. I've instead switched it to adding a hidden property to the tag div so it's always in the DOM and it seems to be working properly now.
Sorry for the flurry of PRs with this element, think it's all finished for now!
PS. Having to submit it looking a little weird, I think the linter is preventing me …
> Activity box fix

- elements/meme-maker/demo/index.html
I don't know why there was so much spacing needed for the demo, so maybe you want to keep it. I thought it was annoying so I deleted it. I also fixed the typo in the memes top-text from "You're" to "Your".
> fixing typo and spacing for meme-maker

- elements/hax-body/lib/hax-plate-context.js
Since we have undo we no longer need a confirm delete step for blocks (the dropdown being an alternative to a confirm modal), so I replaced the dropdown with a button that does not have a confirm step.
> Resolves https://github.com/elmsln/issues/issues/795

- elements/a11y-media-player/lib/a11y-media-state-manager.js
- elements/fullscreen-behaviors/fullscreen-behaviors.js
The a11-media-player manger didn't register player as active until video plays, so if video went to fullscreen before playing, the manager cancelled fullscreen. Now fullscreen mode also makes a player active.
> fixes fullscreen playback issue

- elements/a11y-media-player/a11y-media-player.js
- elements/a11y-media-player/src/a11y-media-player-properties.json
- elements/a11y-media-player/src/a11y-media-player.html
- elements/a11y-media-player/src/a11y-media-player.js
- elements/video-player/src/video-player-hax.json
- elements/video-player/src/video-player-properties.json
- elements/video-player/src/video-player.html
- elements/video-player/src/video-player.js
- elements/video-player/video-player.js
https://github.com/elmsln/issues/issues/145
Need help getting a YouTube button svg for the media player that fits the 24 x 24 specification. This PR currently uses the av:play-arrow icon in place of a YouTube button. The button opens the YouTube page in a new window, hides when it is not a YouTube video, and is disabled with learning mode.
> Draft: Adding Watch on YouTube button

- elements/rich-text-editor/rich-text-editor.js
- elements/rich-text-editor/src/rich-text-editor.js
- elements/simple-fields/lib/simple-fields-combo.js
https://github.com/elmsln/issues/issues/924
Link field is a url field type which uses simple-fields-combo. Combo didn't have a blur event to update form value.
> resolves #924

- elements/simple-fields/lib/simple-fields-lite.js
Properties no longer need to be explicitly added to the element conversions in order to be applied. Resolves https://github.com/elmsln/issues/issues/940
> https://github.com/elmsln/issues/issues/940

- elements/simple-tooltip/src/simple-tooltip.js
Fixed simple-tooltip RTL problem.
This is a non-breaking change adding inset-inline properties that will properly override the left property when needed. Tested in both LTR and RTL.
> RTL tooltip fix

- elements/chat-agent/lib/chat-input.js
Showed my dad the stuff I worked on over the summer and found a bug caused by separating some autoruns lol. The bug basically wouldn't show previous messages in the textarea in the `chat-input` tag when the up arrow was pressed, but would show them when the down arrow was pressed. Fixed by ensuring `this.messageIndex` and `this.previousMessagesIndex` `autorun()` at the same time.
> fixed previous messages not displaying bug

- elements/haxcms-elements/lib/ui-components/blocks/site-children-block.js
- elements/map-menu/lib/map-menu-header.js
- elements/map-menu/lib/map-menu-submenu.js
- elements/polaris-theme/lib/polaris-flex-theme.js
* Updated `site-children-block` wiring to modern mobx implementation, references correct `activeID` values now
* Adjusted position of `polaris-flex-theme` sidebar to better align with the breadcrumb and main text body
* Added an additional `LitElement` property in `map-menu-header`, this allows CSS variables to still apply padding in the flex version
> Some holiday goodies :) (Tweaks to Menu Components)

- elements/simple-tooltip/simple-tooltip.js
I've moved the code I previously added to be dependent upon RTL attribute like is the case in other components. This is due to the fact that sometimes, with absolute positioning - some pages behave differently and therefore need this type of control.
> simple-tooltip RTL support made optional

- elements/simple-tooltip/simple-tooltip.js
Reverts haxtheweb/webcomponents#713
@btopro Really sorry but this change is not needed. Some change in our code led me to believe it was so please revert this. Turns out some forms of containment cause overflow problems and I thought it was the tooltip's fault and it's not. Sorry again.
One thing I would propose is do you want to add position="start" and "end" which will be automatically set to left or right based on the direction of the top level document. This feature does seem to be needed to provide a more seamless experience. Let me know what you think.
> Revert "simple-tooltip RTL support made optional"
