elements/promo-tile/promo-tile.js

Rewrote some css to use flexbox and also reconfigured some html structure.

Rework promo-tile

---

elements/scroll-button/src/scroll-button.css

Added z-index css variable; this will need compiled.

Added z-index property

---

elements/data-viz/data-viz.js
elements/data-viz/demo/index.html
elements/data-viz/src/data-viz.js
elements/multiple-choice/multiple-choice.js
elements/multiple-choice/src/multiple-choice.js
elements/pouch-db/demo/index.html
elements/pouch-db/pouch-db.js
elements/pouch-db/src/pouch-db.js

separated multiple-choice, pouch-db, and data-viz

data-viz now displaying on its own

---

README.md

fixes #278

---

elements/a11y-media-player/a11y-media-player.js
elements/a11y-media-player/lib/a11y-media-behaviors.js
elements/a11y-media-player/src/a11y-media-player.html
elements/a11y-media-player/src/a11y-media-player.js
elements/a11y-tabs/a11y-tabs.js
elements/a11y-tabs/src/a11y-tabs.js
elements/eco-json-schema-form/lib/eco-json-schema-tabs.js
elements/simple-colors/lib/simple-colors-styles.js
elements/simple-colors/simple-colors.js
elements/simple-colors/src/simple-colors.js

- Fixed `eco-json-schema-tabs` empty value error
- Fixed `a11y-tabs` responsive issue #297
- Performance refactor for `simple-colors`!!!!!!!

Improvements to tabs and simple-colors

---

elements/haxcms-elements/lib/core/haxcms-site-editor-ui.js

- feature redirects back to sites pages
- added function redirectToSites()
- tooltip for paper avatar changed

Paper Avatar Icon Redirection

---

elements/map-menu/lib/map-menu-item.js
elements/map-menu/lib/map-menu-submenu.js

https://drive.google.com/file/d/1MvRbabXDks0xbZYH-ZWdNllmeDfPytYK/view?usp=sharing

added else statement to fix icon not changing in map menu fixes #369

---

elements/lrndesign-imagemap/demo/index.html
elements/lrndesign-imagemap/lrndesign-imagemap.js
elements/lrndesign-imagemap/src/lrndesign-imagemap.js

Hi! 
Nikki and I discussed that adjusting and adding a max-height & max-width variable would allow for users to have more flexibility if a content box is larger than previous 300px setting, made changes based on that. Fingers crossed I did the rebase correct and my fork is inline with the main one. :)

 CSS update to simple-popover height and width 

---

elements/lrndesign-sidenote/demo/index.html
elements/lrndesign-sidenote/lrndesign-sidenote.js
elements/lrndesign-sidenote/lrndesign-sidenote.umd.js
elements/lrndesign-sidenote/package.json
elements/lrndesign-sidenote/src/lrndesign-sidenote.js

I'm not sure if the umd.js version is compiling correctly.  Can you check on that to make sure it's ok?

Lrndesign sidenote

---

elements/course-design/lib/course-intro-header.js
elements/course-design/lib/course-intro-lesson-plan.js
elements/course-design/lib/course-intro.js

Added some css properties for controlling the background through vars.
Example:
In your theme.css file add 
```
:root {
--course-intro-header--header--background-size: cover;
--course-intro-bg-color: 47, 88, 123;
} 
```

course-intro changes

---

elements/github-preview/demo/index.html
elements/github-preview/github-preview.js
elements/github-preview/src/github-preview.js

github-preview element modifications

github-preview element modifications

---

elements/simple-fields/demo/upload.html
elements/simple-fields/lib/dist/simple-fields-upload.dev.js
elements/simple-fields/lib/simple-fields-upload.js
elements/simple-login/demo/index.html
elements/simple-login/lib/dist/simple-camera-snap.dev.js
elements/simple-login/lib/dist/simple-login-avatar.dev.js
elements/simple-login/lib/simple-camera-snap.js
elements/simple-login/lib/simple-login-avatar.js
elements/simple-login/lib/simple-login-camera.js
elements/simple-login/simple-login.js
elements/simple-login/src/simple-login.css

Looked at #334, but still needed URL and camera features, so for now I pulled out the picker options as icon buttons so that the upload options are visible at all times.

better upload and login UI

---

elements/media-image/media-image.js
elements/media-image/src/media-image.js

media-image haxHooks integration

media-image haxHooks integration

---

elements/lrnsys-layout/lib/lrnsys-drawer.js

Adding background-color and background-color-hover as CSS variable options for `lrnsys-layout` webcomponent for testing on ELMSLN

Lrnsys drawer updates

---

elements/clean-two/src/clean-two.js
elements/haxcms-elements/lib/core/themes/haxcms-blank-theme.js
elements/haxcms-elements/lib/core/themes/haxcms-slide-theme.js
elements/haxor-slevin/src/haxor-slevin.js
elements/learn-two-theme/learn-two-theme.js
elements/learn-two-theme/src/learn-two-theme.js
elements/outline-player/src/outline-player.js
elements/simple-blog/src/simple-blog.js

for issue https://github.com/elmsln/issues/issues/535

page region stuff for accessibility/screen reader 

---

elements/a11y-collapse/a11y-collapse.js
elements/a11y-collapse/src/a11y-collapse.js

for tab ordering issue https://github.com/elmsln/issues/issues/537
simple fix

fix ally-collapse tabing issue

---

elements/hex-picker/demo/index.html
elements/hex-picker/hex-picker.js
elements/hex-picker/src/hex-picker.js

- input validation
- disabled state
- large view
- opacity option
- custom event implmentation
- hax properties
- css vars

hex-picker improvements

---

elements/hex-picker/hex-picker.js
elements/hex-picker/src/hex-picker.js

hex-picker fixes

---

elements/clean-two/clean-two.js
elements/clean-two/src/clean-two.js

- account for device width under 400px

haxtheweb.org mobile responsiveness

---

elements/hax-body/lib/hax-plate-context.js

This feels like a hacky workaround, let me know what you think.

double click delete to remove element

---

elements/github-preview/github-preview.js
elements/github-preview/package.json
elements/github-preview/src/github-preview.js
elements/github-preview/test/github-preview.test.js

- added some of open-wc and modern web testing to github-preview

modern testing example

---

.github/workflows/build.yml

I may have deleted it thinking it didn't work, then it was merged without the code.

Readd elements readme action

---

README.md
scripts/lrnwebcomponentsme.sh
scripts/postinstall.sh

quick install script and readme update

quick install script

---

elements/figure-label/src/figure-label.css

Added css variables to title and description selectors for color flexibility.

Updated figure-label.css with css variables

---

elements/hax-body/hax-body.js
elements/hax-body/lib/hax-plate-context.js
elements/hax-body/lib/hax-text-editor-paste-button.js
elements/hax-body/lib/hax-text-editor-toolbar.js
elements/hax-body/src/hax-body.js
elements/rich-text-editor/lib/buttons/rich-text-editor-link.js

- add column button back on grid-plat
- allowLinkTarget property ton hax-body enables link targets on text toolbar
- fixes error with link label
- fixes unlink dup error

add column button back on grid-plate and 

---

elements/a11y-figure/a11y-figure.js
elements/a11y-figure/src/a11y-figure.js
elements/h-a-x/h-a-x.js
elements/h-a-x/src/h-a-x.js
elements/hax-body-behaviors/lib/HAXWiring.js
elements/hax-body/demo/appstore.json
elements/hax-body/demo/bueller.vtt
elements/hax-body/demo/index.html
elements/hax-body/lib/hax-gizmo-browser.js
elements/hax-body/lib/hax-store.js
elements/hax-body/lib/hax-tray.js
elements/hax-iconset/lib/svgs/hax/figure.svg
elements/rich-text-editor/lib/toolbars/rich-text-editor-breadcrumbs.js
elements/rich-text-editor/lib/toolbars/rich-text-editor-toolbar.js
elements/simple-fields/lib/simple-fields-field.js
elements/simple-fields/lib/simple-fields-upload.js

- Resolves an issue with the upload field's text input
- Adds figure to hax

Resolves an issue with the upload field's text input

---

elements/haxcms-elements/lib/core/utils/HAXCMSMobileMenu.js
elements/haxcms-elements/lib/core/utils/HAXCMSRememberRoute.js

still having problems using the menuOpen variable even though it is set correctly

#813 save menuOpen to local storage

---

.editorconfig
scripts/lrnwebcomponentsme.sh

Hi, I noticed that `scripts/lrnwebcomponentsme.sh` contains both spaces and tabs as indentations. This PR just replaces tabs with spaces according to `.editorconfig`.

Fix indentations of script

---

elements/course-design/lib/course-intro-footer.js
elements/course-design/lib/course-intro-header.js
elements/course-design/lib/course-intro-lesson-plan.js
elements/course-design/lib/course-intro-lesson-plans.js
elements/course-design/lib/course-intro.js

For use of a much better course-intro, please accept this PR.

course-intro redesign

---

elements/hax-body/lib/hax-text-editor-toolbar.js
elements/rich-text-editor/demo/config.html
elements/rich-text-editor/lib/singletons/rich-text-editor-range-behaviors.js
elements/rich-text-editor/lib/toolbars/rich-text-editor-toolbar.js

- Added ability to add simple inline element buttons like, <code>.
- Added code button to HAX text editor toolbar.
- Fixed some random issues with text selection reverting to previous selection in editor.

<code> button

---

elements/d-d-d/d-d-d.js
elements/d-d-d/demo/index.html
elements/d-d-d/src/d-d-d.js
package.json

Started creating css classes to be used in the future
P.S. ignore the astronomically large amount of code, most of it is syntax for being able to add margin & padding classes (ex. p-5, mb-28) based on comp

Beginning of design patterns for HAX

---

elements/media-quote/demo/index.html

Media quote demo updated to include three total demos:
1. Standard demo, just the component.
2. Component with a slider above it so the user can see what it looks like to change the color themes
3. `<grid-plate>` wrapped around two `<media-quote>` to showcase `@component{}` CSS queries

Updated <media-quote> demo

---

elements/hax-body/lib/hax-store.js

Resolves issue of "Submit bug report" button not working due to invalid navigator path.  `navigator.userAgent.platform` is not a valid path in Firefox or Safari since [`userAgentData` is not supported in those browsers (for some reason???).](https://caniuse.com/?search=userAgentData) Regardless, this should fix those issues, worked for me on localhost with a user agent switcher for testing Windows, iOS, macOS, Linux, and Android, and also tested on Firefox, Chrome, and Gnome Web (closest I could get to Safari testing on Linux with it running Webkit).
This fixed the issue when pressing the feature request button as well.
https://github.com/haxtheweb/issues/issues/2075
https://github.com/haxtheweb/issues/issues/1688
Note: I could **not** find a work around for …

Fixes #2075

---

elements/a11y-collapse/a11y-collapse.js
elements/haxcms-elements/lib/core/utils/HAXCMSMobileMenu.js
elements/haxcms-elements/lib/ui-components/navigation/site-menu.js
elements/map-menu/lib/map-menu-builder.js
elements/map-menu/lib/map-menu-header.js
elements/map-menu/lib/map-menu-item.js
elements/map-menu/lib/map-menu-submenu.js
elements/map-menu/map-menu.js
elements/polaris-theme/lib/polaris-flex-theme.js

* Implemented new `LitElement` properties to track orientation and depth states
* New `HAXCMSFlexMenu` function call added to `HAXCMSMobileMenu` coreutil, hooks with the `responsiveSize` utility
* `Map-menu` responsively adapts between a horizontal desktop state and vertical mobile state
* CSS `Grid` and `Flexbox` used to dynamically align menu items according to available columns
* CSS variables added for each layer to expand customization and fine tune formatting for unique themes
* Conditional CSS and web component rendering to maintain backwards compatibility with legacy vertical `map-menu`
* haxtheweb/issues#2023

Refactored map-menu implementation for flexible theme development

---

elements/clean-portfolio-theme/clean-portfolio-theme.js

Added changes from https://github.com/haxtheweb/issues/issues/2264

portfolio theme - enhancements

---

README.md

https://github.com/haxtheweb/issues/issues/2302

Issue #2302

---

elements/clean-portfolio-theme/clean-portfolio-theme.js

Implements a fix for https://github.com/haxtheweb/issues/issues/2298, along with additional discussed requirements.

portfolio theme - responsiveness, fade transitions, new footer, etc.

---

elements/clean-portfolio-theme/clean-portfolio-theme.js

https://github.com/haxtheweb/issues/issues/2307

clean-portfolio-theme - https://github.com/haxtheweb/issues/issues/2307
